name: Main

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create a PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          echo "Creating a PR" >> notes.md
          git checkout -b $GITHUB_SHA
          git add notes.md
          git commit -m "Add notes.md"
          git push origin $GITHUB_SHA
          gh pr create --title "Hello World" --body "This is a test PR"
